### ISSUE TITLE
How does one use the OTA functionality?

### ISSUE THREAD

**Issue by S2Doc** [sskorol/arduino-network#1]
It is unclear from the generic example how one implements OTA.  Does it need to be pushed from a server?  What exactly is the pushed file?  Is it to be pulled by the IoT device?  

Does the OTA portion of this library work with non-ESP MCUs, such as ARM M4 (SAMD21)?

**Comment by sskorol** [comment]
@S2Doc it's just a wrapper around ArduinoOTA (to reduce boilerplate).
The initial update should be done via a serial port. Then, in case of PlarformIO usage, you can add the following lines into .ini:
```
upload_protocol = espota
upload_port = ip.address
upload_flags =
  --port=8266
```
Recompile and that's it. Now you can disconnect the cable and push the update via OTA.

Haven't tested it on other platforms.

**Comment by S2Doc** [comment]
Thanks for the reply, @sskorol !
Is upload_port = ip.address automatically resolved by PlatformIO?

**Comment by sskorol** [comment]
@S2Doc no, you should assign it manually, and it should be equal to the ip address you specified for WiFiClient configuration (device ip).

**Comment by S2Doc** [comment]
So, I will need to assign each device a fixed IP addresses and have a different platformio.ini for each?  There will be thousands of devices in the field, each getting its IP address from it's wifi Access Point using DHCP.

**Comment by sskorol** [comment]
You can pass it through env variable. But in that case, it seems that you also need a separate devices' management service.

**Comment by S2Doc** [comment]
Thanks for your help!
