### ISSUE TITLE
ESP32 not compiling but tagged

### ISSUE THREAD

**Issue by exocode** [sskorol/arduino-network#2]
Hi there, 
I found your lib via PlatformIO (see here https://platformio.org/lib/show/6373/arduino-network).

It is tagged as "working with ESP32 / Espressif32" but it wont compile: 

```

Compiling .pio/build/heltec_wifi_kit_32/libf20/arduino-network_ID6373/Helpers.cpp.o
In file included from .pio/libdeps/heltec_wifi_kit_32/arduino-network_ID6373/src/Helpers.cpp:1:0:
.pio/libdeps/heltec_wifi_kit_32/arduino-network_ID6373/include/Helpers.hpp:4:25: fatal error: ESP8266WiFi.h: No such file or directory

*********************************************************************
* Looking for ESP8266WiFi.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:ESP8266WiFi.h"
* Web  > https://platformio.org/lib/search?query=header:ESP8266WiFi.h
*
*********************************************************************


compilation terminated.
Compiling .pio/build/heltec_wifi_kit_32/libf20/arduino-network_ID6373/MqttClient.cpp.o
Compiling .pio/build/heltec_wifi_kit_32/libf20/arduino-network_ID6373/OtaServer.cpp.o
Compiling .pio/build/heltec_wifi_kit_32/libf20/arduino-network_ID6373/WifiClient.cpp.o
In file included from .pio/libdeps/heltec_wifi_kit_32/arduino-network_ID6373/src/OtaServer.cpp:1:0:
.pio/libdeps/heltec_wifi_kit_32/arduino-network_ID6373/include/OtaServer.hpp:4:24: fatal error: ArduinoOTA.h: No such file or directory

********************************************************************
* Looking for ArduinoOTA.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:ArduinoOTA.h"
* Web  > https://platformio.org/lib/search?query=header:ArduinoOTA.h
*
********************************************************************

compilation terminated.
In file included from .pio/libdeps/heltec_wifi_kit_32/arduino-network_ID6373/include/MqttClient.hpp:6:0,
                 from .pio/libdeps/heltec_wifi_kit_32/arduino-network_ID6373/src/MqttClient.cpp:1:
.pio/libdeps/heltec_wifi_kit_32/arduino-network_ID6373/include/WifiClient.hpp:5:25: fatal error: ESP8266WiFi.h: No such file or directory

*********************************************************************
* Looking for ESP8266WiFi.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:ESP8266WiFi.h"
* Web  > https://platformio.org/lib/search?query=header:ESP8266WiFi.h
*
*********************************************************************

compilation terminated.
Compiling .pio/build/heltec_wifi_kit_32/FrameworkArduino/HardwareSerial.cpp.o
In file included from .pio/libdeps/heltec_wifi_kit_32/arduino-network_ID6373/src/WifiClient.cpp:1:0:
.pio/libdeps/heltec_wifi_kit_32/arduino-network_ID6373/include/WifiClient.hpp:5:25: fatal error: ESP8266WiFi.h: No such file or directory

*********************************************************************
* Looking for ESP8266WiFi.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:ESP8266WiFi.h"
* Web  > https://platformio.org/lib/search?query=header:ESP8266WiFi.h
*
*********************************************************************

compilation terminated.
Compiling .pio/build/heltec_wifi_kit_32/FrameworkArduino/IPAddress.cpp.o
Compiling .pio/build/heltec_wifi_kit_32/FrameworkArduino/IPv6Address.cpp.o
*** [.pio/build/heltec_wifi_kit_32/libf20/arduino-network_ID6373/Helpers.cpp.o] Error 1
Compiling .pio/build/heltec_wifi_kit_32/FrameworkArduino/MD5Builder.cpp.o
*** [.pio/build/heltec_wifi_kit_32/libf20/arduino-network_ID6373/OtaServer.cpp.o] Error 1
*** [.pio/build/heltec_wifi_kit_32/libf20/arduino-network_ID6373/MqttClient.cpp.o] Error 1
*** [.pio/build/heltec_wifi_kit_32/libf20/arduino-network_ID6373/WifiClient.cpp.o] Error 1
============================= [FAILED] Took 2.19 seconds =============================
The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.


```

I tried to make a conditional switch between ESP32 and ESP8266 like so: 

```
#ifdef ARDUINO_ARCH_ESP32
  #include <WiFi.h>
#elif defined(ARDUINO_ARCH_ESP8266)
  #include <ESP8266WiFi.h>
#endif
```

But I stuck then in the next issue: 

```
In file included from /Users/jan/.platformio/packages/framework-arduinoespressif32/libraries/ArduinoOTA/src/ArduinoOTA.cpp:6:0:
/Users/jan/.platformio/packages/framework-arduinoespressif32/libraries/ArduinoOTA/src/ArduinoOTA.h:6:20: fatal error: Update.h: No such file or directory
```

Do I have to use another Lib for my approach? 
Or is there a possibility to make the compiler happy?

Thank you!

**Comment by sskorol** [comment]
Hi @exocode,

My bad, I've specified `*` in platforms section. Both `ArduinoOTA` and `ESP8266WiFi` refer to https://github.com/esp8266/Arduino/tree/master/libraries

Will fix that in the next version. Sorry for inconveniences.

**Comment by exocode** [comment]
No problem. Is it possible to make both of them working then?
I am searching an easy solution to make OTA on ESP32 and ESP8266, is your lib the right one?

Thank you

**Comment by sskorol** [comment]
@exocode I'll add wi-fi and dns switch support. However, your issue is a bit different.

Seems like there's a problem detecting
https://github.com/espressif/arduino-esp32/blob/master/libraries/Update/src/Update.h dependency, which is a part of ArduinoOTA for esp32.

That's weird if it's not found for you. Will try to forcibly add it as well.
Don't have esp32 to test right now. So will ask you to double-check when a new version is published.

**Comment by exocode** [comment]
Sounds great! Thank you!

**Comment by sskorol** [comment]
I've updated a project. However, it's not yet synced with platformio registry.
In the meantime, you can try to use this version by direct url.

**Comment by sskorol** [comment]
@exocode seems like it's already synced, so you can check.

**Comment by exocode** [comment]
I also found, that `JSON_BUFFER_SIZE` was not defined. Is it my choice?

`const unsigned int JSON_BUFFER_SIZE = 1024;` must be placed somewhere..

**Comment by sskorol** [comment]
@exocode if you're talking about provided example, I intentionally left several variables unset, assuming end-users will decide where they want to put those vars. Personally I pass such things via `build_flags` in `platformio.ini`. Alternatively, you can set it in a header file of course.

P.S. So have you tried an updated version? Does it compile on esp32?

**Comment by exocode** [comment]
When I add the example in `/src/main.cpp` It asks for `EntryPoint.hpp`. 
- After copying `EntryPoint.hpp` into `/include`
- adding `lib_deps = ArduinoJson` into `platformio.ini`
- and setting the `JSON_BUFFER_SIZE ` in `main.cpp` to `const unsigned int JSON_BUFFER_SIZE = 1024;` 

it compiles :-)

**Comment by sskorol** [comment]
@exocode these steps are related only to the provided example. They don't affect the library itself.

Moreover, you don't need to include `MqttClient` / `MqttConfig` to use `OTAServer`. It's just a generic example which includes all the parts of the library.

If you need a WiFi wrapper, you may include only `WifiClient.hpp`. If you need OTA -> `OtaServer.hpp`. Mqtt -> `WifiClient.hpp` + `MqttClient.hpp`.

`ArduinoJson` dependency is not required as well. You can handle mqtt callback payload the way you want, w/o json processing.

But on the other hand, I can see that it's worth to update README with some clarifications to avoid confusion in the future.

Thanks!
